blank_issues_enabled: true
contact_links:
- name: Ideas & Feature Requests
  url: https://github.com/TheSuperHackers/GeneralsGameCode/discussions/categories/ideas
  about: Request an idea or feature request to be added to the game.
- name: Community Outpost Discord Server
  url: https://discord.gg/WzxQDZersE
  about: For help with miscelleneous things, join our discord server!
